import 'bootstrap/dist/css/bootstrap.min.css';
import '@chatscope/chat-ui-kit-styles/dist/default/styles.min.css';
import './assets/css/style.css';

import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="d-flex flex-column justify-content-between vh-100">
          <div className="d-flex flex-column">
            <Header />
            <div className="container">
              {children}
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
